# Makefile for FINC450 Lifecycle Investment Strategy figures
#
# Usage:
#   make          - Generate all figures and PDFs
#   make figures  - Generate lecture figures only
#   make pdfs     - Generate PDF reports only
#   make clean    - Remove all generated files

PYTHON = python3
FIGURES_DIR = figures
FIGURE_FORMAT = png
FIGURE_DPI = 150

# Output files
LIFECYCLE_PDF = lifecycle_strategy.pdf
DASHBOARD_PDF = strategy_dashboard.pdf

# Figure files (generated by generate_lecture_figures.py)
FIGURE_FILES = $(FIGURES_DIR)/01_income_expenses.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/02_cash_flow.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/03_present_values.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/04_wealth_composition.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/05_gauges_dashboard.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/06_allocation_theory.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/07_duration_matching.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/08_consumption_path.$(FIGURE_FORMAT) \
               $(FIGURES_DIR)/09_beta_comparison.$(FIGURE_FORMAT)

# Source files that trigger rebuilds
CORE_SOURCES = core/params.py core/economics.py core/simulation.py core/strategies.py
VIZ_SOURCES = visualization/styles.py visualization/helpers.py \
              visualization/lifecycle_plots.py visualization/monte_carlo_plots.py \
              visualization/comparison_plots.py visualization/sensitivity_plots.py

.PHONY: all figures pdfs clean help

# Default target: build everything
all: figures pdfs

# Generate all lecture figures
figures: $(FIGURES_DIR)/.stamp

$(FIGURES_DIR)/.stamp: generate_lecture_figures.py $(CORE_SOURCES) $(VIZ_SOURCES)
	@echo "Generating lecture figures..."
	$(PYTHON) generate_lecture_figures.py --output-dir $(FIGURES_DIR) --format $(FIGURE_FORMAT) --dpi $(FIGURE_DPI)
	@touch $@

# Generate all PDFs
pdfs: $(LIFECYCLE_PDF) $(DASHBOARD_PDF)

# Lifecycle strategy PDF
$(LIFECYCLE_PDF): lifecycle_strategy.py $(CORE_SOURCES) $(VIZ_SOURCES)
	@echo "Generating $(LIFECYCLE_PDF)..."
	$(PYTHON) lifecycle_strategy.py -o $@

# Strategy dashboard PDF
$(DASHBOARD_PDF): dashboard.py $(CORE_SOURCES) $(VIZ_SOURCES)
	@echo "Generating $(DASHBOARD_PDF)..."
	$(PYTHON) dashboard.py

# Create figures directory
$(FIGURES_DIR):
	mkdir -p $(FIGURES_DIR)

# Clean generated files
clean:
	@echo "Cleaning generated files..."
	rm -f $(LIFECYCLE_PDF) $(DASHBOARD_PDF)
	rm -rf $(FIGURES_DIR)
	rm -f *.aux *.log *.nav *.out *.snm *.toc
	@echo "Done."

# Help
help:
	@echo "FINC450 Lifecycle Investment Strategy - Makefile"
	@echo ""
	@echo "Targets:"
	@echo "  all      - Generate all figures and PDFs (default)"
	@echo "  figures  - Generate lecture figures ($(FIGURES_DIR)/)"
	@echo "  pdfs     - Generate PDF reports"
	@echo "  clean    - Remove all generated files"
	@echo "  help     - Show this help message"
	@echo ""
	@echo "Output files:"
	@echo "  $(LIFECYCLE_PDF)    - Main lifecycle strategy analysis"
	@echo "  $(DASHBOARD_PDF)   - Strategy comparison dashboard"
	@echo "  $(FIGURES_DIR)/             - Lecture figures (PNG)"
